# Four wave mixing simulation

In [9]:
import numpy as np

# Conservation of energy
$$
2 \omega_{p} = \omega_{s} + \omega_{i}
$$

$\omega_{s}$ is the signal frequency which corresponds to the shorter wavelength photon produced in four wave mixing.  
$\omega_{i}$ is the idler frequency which corresponds to the longer wavelength photon produced in four wave mixing process.  
$\omega_{p}$ is the pump frequency

# Conservation of momentum
$$
2\beta(\omega_{p}) = \beta(\omega_{s}) + \beta(\omega_{i}) + 2\gamma P
$$
Subtracting all onto one side gives
$$
2\beta(\omega_{p}) - \beta(\omega_{s}) - \beta(\omega_{i}) - 2\gamma P = 0
$$

$\gamma$ is approximately $0.2Wm^{-1}$  and $P$ is approximately equal to $100W$

Mid IR wavelengths range roughly from 2500–25000nm  
This corresponds to frequencies of 1.2*10^13 to 1.2*10^14  
Which corresponds to angular frequencies of 2 $\pi$ * these frequencies

Will be using 1 micron to 1.6 microns for pump wavelength, with 100 points for spacing.  
Signal needs a slightly larger range because the solution we are expecting is steeper in the shorter wavelength range.  
100 by 100 matrices should work fine. Anything bigger than 200 by 200 will be too slow.

In [10]:
# Function to convert wavelength to angular frequency
def lambda_to_ang_freq(wavelength_matrix):
    return (2*np.pi*3e8) / wavelength_matrix

In [11]:
# PUMP WAVELENGTH MATRIX

def create_pump_matrix(rows, columns, start_value, step):
    matrix = np.zeros((rows, columns))
    for i in range(columns):
        matrix[:, i] = np.full(rows, start_value + i * step)
    return matrix

# Number of rows and columns, start and end values for the pump wavelengths, and calculating the spacing between each column value
rows = 5
columns = 5
start_value = 1e-6
end_value = 1.6e-6
step = (end_value - start_value) / columns

pump_wavelength_matrix = create_pump_matrix(rows, columns, start_value, step)
pump_frequency_matrix = lambda_to_ang_freq(pump_wavelength_matrix)
pump_frequency_matrix
#print(pump_wavelength_matrix)

array([[1.88495559e+15, 1.68299606e+15, 1.52012548e+15, 1.38599676e+15,
        1.27361864e+15],
       [1.88495559e+15, 1.68299606e+15, 1.52012548e+15, 1.38599676e+15,
        1.27361864e+15],
       [1.88495559e+15, 1.68299606e+15, 1.52012548e+15, 1.38599676e+15,
        1.27361864e+15],
       [1.88495559e+15, 1.68299606e+15, 1.52012548e+15, 1.38599676e+15,
        1.27361864e+15],
       [1.88495559e+15, 1.68299606e+15, 1.52012548e+15, 1.38599676e+15,
        1.27361864e+15]])

In [12]:
#SIGNAL WAVELENGTH MATRIX

def create_matrix(rows, columns, min_value, max_value):
    matrix = np.zeros((rows, columns))
    for i in range(columns):
        matrix[:, i] = np.linspace(min_value, max_value, rows)
    return matrix

# Example usage
rows = 5
columns = 5
min_value = 0.5e-6
max_value = 2.6e-6

signal_wavelength_matrix = create_matrix(rows, columns, min_value, max_value)
signal_frequency_matrix = lambda_to_ang_freq(signal_wavelength_matrix)
print(signal_wavelength_matrix)

[[5.000e-07 5.000e-07 5.000e-07 5.000e-07 5.000e-07]
 [1.025e-06 1.025e-06 1.025e-06 1.025e-06 1.025e-06]
 [1.550e-06 1.550e-06 1.550e-06 1.550e-06 1.550e-06]
 [2.075e-06 2.075e-06 2.075e-06 2.075e-06 2.075e-06]
 [2.600e-06 2.600e-06 2.600e-06 2.600e-06 2.600e-06]]


In [13]:
# CALCULATION TO GET IDLER WAVELENGTH MATRIX

idler_wavelength_matrix = 2*pump_wavelength_matrix - signal_wavelength_matrix #Using cons of energy equation
idler_frequency_matrix = lambda_to_ang_freq(idler_wavelength_matrix) # Converting to angular frequency in prep for
idler_frequency_matrix

array([[ 1.25663706e+15,  1.08330781e+15,  9.51997774e+14,
         8.49079096e+14,  7.66242111e+14],
       [ 1.93328779e+15,  1.55140378e+15,  1.29550213e+15,
         1.11206820e+15,  9.74137257e+14],
       [ 4.18879020e+15,  2.73181970e+15,  2.02683397e+15,
         1.61107316e+15,  1.33684794e+15],
       [-2.51327412e+16,  1.14239733e+16,  4.65421134e+15,
         2.92241177e+15,  2.12989332e+15],
       [-3.14159265e+15, -5.23598776e+15, -1.57079633e+16,
         1.57079633e+16,  5.23598776e+15]])

## Input all pump and signal frequencies into beta, then calculate matrix of $\beta(\omega_{i})$ so we can plot it and see if we get expected shape

In [23]:
# Beta for fused silica as a function of angular frequency we found from previous work.
pump_frequency_matrix

array([[1.88495559e+15, 1.68299606e+15, 1.52012548e+15, 1.38599676e+15,
        1.27361864e+15],
       [1.88495559e+15, 1.68299606e+15, 1.52012548e+15, 1.38599676e+15,
        1.27361864e+15],
       [1.88495559e+15, 1.68299606e+15, 1.52012548e+15, 1.38599676e+15,
        1.27361864e+15],
       [1.88495559e+15, 1.68299606e+15, 1.52012548e+15, 1.38599676e+15,
        1.27361864e+15],
       [1.88495559e+15, 1.68299606e+15, 1.52012548e+15, 1.38599676e+15,
        1.27361864e+15]])

In [18]:
import RefractiveIndexClass

In [25]:
result_array = RefractiveIndexClass.RefractiveIndex.n_fs(pump_frequency_matrix,parameter="omega")
result_array

array([[1.45041741, 1.44896961, 1.44759631, 1.44623664, 1.4448526 ],
       [1.45041741, 1.44896961, 1.44759631, 1.44623664, 1.4448526 ],
       [1.45041741, 1.44896961, 1.44759631, 1.44623664, 1.4448526 ],
       [1.45041741, 1.44896961, 1.44759631, 1.44623664, 1.4448526 ],
       [1.45041741, 1.44896961, 1.44759631, 1.44623664, 1.4448526 ]])

# Modelling for HCF filled with noble gas

Equation 22 of Markos paper will let us calculate the bulk refractive index of the gas in the fibre.  
$$ n^{2}_{gas} - 1 = Re(\chi_{e}) =  \sum_{t}^{} \frac{N_{t}}{N_{t,0}}Re(\chi_{t,e})  $$  
Or can use this equation from Borzsonyi 2008 paper:  
$$ n^{2}(\lambda,p,T) - 1 = \frac{p}{p_{0}}\frac{T_{0}}{T} [\frac{B_{1}\lambda^{2}}{\lambda^{2}-C_{1}} + \frac{B_{2}\lambda^{2}}{\lambda^{2}-C_{2}}] $$